version: "3.9"
services:
  web:
    container_name: universal_auto_web
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    ports:
      - "8000:8000"
      - "80:80"
    command: honcho start
    volumes:
      - .:/app

    environment:
      TELEGRAM_TOKEN: 
      UBER_NAME: 
      UBER_PASSWORD: 
      BOLT_NAME: 
      BOLT_PASSWORD: 
      UKLON_NAME: 
      UKLON_PASSWORD:
      PRIVAT24_NAME:              #lenght = 9 ex: 632587413
      PRIVAT24_PASSWORD:
      PORTMONE_LOGIN:
      PORTMONE_PASSWORD:
      PORTMONE_PAYEE_ID:
      REDIS_URL: redis://redis
      DATABASE_URL: "postgres://universal_auto_dev:pass@postgres:5432/universal_auto_dev"
      SECRET_KEY: 
      UDP_IP: 0.0.0.0
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      SELENIUM_HUB_HOST: http://chrome:4444/wd/hub
      DEBUG: "False"
      ALLOWED_HOSTS: 127.0.0.1 0.0.0.0 localhost
      CSRF_TRUSTED_ORIGINS: "http://127.0.0.1 http://168.220.93.200 http://localhost"

  redis:
    container_name: universal_auto_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    container_name: universal_auto_postgres
    image: postgres:13.8
    environment:
      POSTGRES_DB: "universal_auto_dev"
      POSTGRES_USER: "universal_auto_dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U universal_auto_dev -d universal_auto_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  pgadmin:
    container_name: universal_auto_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "universal_auto_dev@example.com"
      PGADMIN_DEFAULT_PASSWORD: "universal_auto_dev"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  chrome:
    container_name: universal_auto_chrome
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    restart: always
    environment:
      SE_NODE_SESSION_TIMEOUT: 600
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_MAX_INSTANCES: 5
