# Generated by Django 4.0.5 on 2022-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField()),
                ('driver_uuid', models.UUIDField()),
                ('drievr_name', models.CharField(max_length=30)),
                ('drievr_second_name', models.CharField(max_length=30)),
                ('trip_uuid', models.UUIDField()),
                ('trip_description', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_nickname', models.CharField(max_length=50)),
                ('transaction_time', models.DateTimeField()),
                ('paid_to_you', models.DecimalField(decimal_places=2, max_digits=5)),
                ('your_earnings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fare2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wait_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('out_of_city', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transfered_to_bank', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ajustment_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cancel_payment', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
