# Generated by Django 4.0.5 on 2022-10-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoltPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('report_file_name', models.CharField(max_length=255)),
                ('driver_full_name', models.CharField(max_length=24)),
                ('mobile_number', models.CharField(max_length=13)),
                ('range_string', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancels_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorization_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorization_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_cach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_cash_trips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField()),
                ('driver_uuid', models.UUIDField()),
                ('driver_name', models.CharField(max_length=30)),
                ('driver_second_name', models.CharField(max_length=30)),
                ('trip_uuid', models.CharField(max_length=255)),
                ('trip_description', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_nickname', models.CharField(max_length=50)),
                ('transaction_time', models.DateTimeField()),
                ('paid_to_you', models.DecimalField(decimal_places=2, max_digits=10)),
                ('your_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fare2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wait_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_city', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfered_to_bank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajustment_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancel_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UberPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('report_file_name', models.CharField(max_length=255)),
                ('driver_uuid', models.UUIDField()),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_clean_amout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_cach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfered_to_bank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UklonPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('report_file_name', models.CharField(max_length=255)),
                ('signal', models.CharField(max_length=8)),
                ('licence_plate', models.CharField(max_length=8)),
                ('total_rides', models.PositiveIntegerField()),
                ('total_distance', models.PositiveIntegerField()),
                ('total_amount_cach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_cach_less', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_without_comission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=20)),
                ('report_file_name', models.CharField(max_length=255, unique=True)),
                ('report_from', models.CharField(max_length=10)),
                ('report_to', models.CharField(max_length=10)),
                ('file', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
