# Generated by Django 4.0.5 on 2022-08-22 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uklonpaymentsorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('report_file_name', models.CharField(max_length=255)),
                ('driver_full_name', models.CharField(max_length=24)),
                ('mobile_number', models.CharField(max_length=12)),
                ('range_string', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancels_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorization_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorization_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_cach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_cash_trips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UberPaymentsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField()),
                ('report_to', models.DateTimeField()),
                ('report_file_name', models.CharField(max_length=255)),
                ('driver_uuid', models.UUIDField()),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_clean_amout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_cach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfered_to_bank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returns', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paymentsorder',
            old_name='drievr_name',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='paymentsorder',
            old_name='drievr_second_name',
            new_name='driver_second_name',
        ),
        migrations.AddField(
            model_name='uklonpaymentsorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uklonpaymentsorder',
            name='report_file_name',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uklonpaymentsorder',
            name='report_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uklonpaymentsorder',
            name='report_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uklonpaymentsorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
