# Generated by Django 4.0.5 on 2022-10-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filenameprocessed_fleet_ubertransactions_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='drivermanager',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='servicestationmanager',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='supportmanager',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='CLIENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='support_manager_id',
            field=models.ManyToManyField(blank=True, to='app.supportmanager'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_manager_id',
            field=models.ManyToManyField(blank=True, to='app.drivermanager'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fleet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fleet'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='partner_id',
            field=models.ManyToManyField(blank=True, to='app.partner'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='DRIVER', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehicle'),
        ),
        migrations.AlterField(
            model_name='drivermanager',
            name='driver_id',
            field=models.ManyToManyField(blank=True, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='drivermanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='DRIVER_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='driver_id',
            field=models.ManyToManyField(blank=True, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fleet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fleet'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='PARTNER', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicestationmanager',
            name='driver_id',
            field=models.ManyToManyField(blank=True, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='servicestationmanager',
            name='fleet_id',
            field=models.ManyToManyField(blank=True, to='app.fleet'),
        ),
        migrations.AlterField(
            model_name='servicestationmanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='SERVICE_STATION_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportmanager',
            name='client_id',
            field=models.ManyToManyField(blank=True, to='app.client'),
        ),
        migrations.AlterField(
            model_name='supportmanager',
            name='driver_id',
            field=models.ManyToManyField(blank=True, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='supportmanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager')], default='SUPPORT_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
