# Generated by Django 4.0.5 on 2022-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_boltpaymentsorder_uberpaymentsorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uberpaymentsorder',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
