# Generated by Django 4.0.5 on 2022-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uberpaymentsorder_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=20)),
                ('report_file_name', models.CharField(max_length=255, unique=True)),
                ('report_from', models.CharField(max_length=10)),
                ('report_to', models.CharField(max_length=10)),
                ('file', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
