# Generated by Django 4.0.5 on 2022-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_newuklonpaymentsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuklonpaymentsorder',
            name='total_amount_on_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
