# Generated by Django 4.0.5 on 2022-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fleets_drivers_vehicles_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boltpaymentsorder',
            name='mobile_number',
            field=models.CharField(max_length=24),
        ),
    ]
