# Generated by Django 4.0.5 on 2022-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_boltpaymentsorder_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
